"""Async function throttling utilities."""

import asyncio
from collections.abc import AsyncGenerator
from typing import TypeVar

# Define a type variable for the items generated by the asynchronous generator
T = TypeVar("T")


async def async_throttle(
    generator: AsyncGenerator[T, None], delay: float
) -> AsyncGenerator[T, None]:
    """
    Throttle an asynchronous generator by adding a delay between items.

    Parameters
    ----------
    generator : AsyncGenerator[T, None]
        The asynchronous generator to throttle.
    delay : float
        The delay in seconds between each generated item.

    Returns
    -------
    AsyncGenerator[T, None]
        An asynchronous generator yielding items from ``generator`` delayed by
        the specified amount.

    Raises
    ------
    TypeError
        If ``delay`` is not a float.
    ValueError
        If ``delay`` is negative.
    Exception
        Propagates any exception raised by the underlying ``generator``.

    Examples
    --------
    >>> async def my_generator():
    >>>     for i in range(5):
    >>>         yield i
    >>>
    >>> async for value in async_throttle(my_generator(), delay=1):
    >>>     print(value)
    0
    (1-second delay)
    1
    (1-second delay)
    2
    """
    if not isinstance(delay, (int, float)):
        raise TypeError("delay must be a float")

    if delay < 0:
        msg = "delay must be non-negative"
        raise ValueError(msg)

    # Iterate over the items in the generator
    first_item = True
    async for item in generator:
        if not first_item and delay:
            # Introduce a delay before yielding the next item. Sleeping before
            # yielding ensures that the consumer observes the throttled spacing
            # directly between consecutive values and avoids an unnecessary
            # trailing sleep once the generator is exhausted.
            await asyncio.sleep(delay)
        first_item = False
        # Yield the current item
        yield item


__all__ = ["async_throttle"]
