from typing import TypeVar
from collections.abc import Iterable, Awaitable
import asyncio

# Define a type variable for the items generated by the asynchronous generator
T = TypeVar("T")


async def gather_with_timeout(
    awaitables: Iterable[Awaitable[T]], timeout: float
) -> list[T]:
    """
    Gather asynchronous awaitables and enforce a timeout.

    Parameters
    ----------
    awaitables : Iterable[Awaitable[T]]
        Iterable of awaitable objects (e.g., coroutines) to execute. Each
        awaitable is wrapped in an ``asyncio.Task`` via ``asyncio.create_task``.
    timeout : float
        The maximum time in seconds to wait for the awaitables to complete.

    Returns
    -------
    list[T]
        The results of the awaitables that completed before the timeout.

    Raises
    ------
    asyncio.TimeoutError
        If the awaitables do not complete within the given timeout.

    Examples
    --------
    >>> async def long_task(i: int) -> int:
    >>>     await asyncio.sleep(i)
    >>>     return i
    >>> coros = [long_task(1), long_task(2), long_task(3)]
    >>> asyncio.run(gather_with_timeout(coros, timeout=2))
    [1, 2]
    """
    tasks = [asyncio.create_task(aw) for aw in awaitables]
    try:
        return await asyncio.wait_for(asyncio.gather(*tasks), timeout=timeout)
    except asyncio.TimeoutError:
        return await asyncio.gather(*[t for t in tasks if not t.cancelled()])

__all__ = ['gather_with_timeout']
